### PR TITLE
Use the standard npx affordance to run the versions of our dependencies we've packaged.

### PR DESCRIPTION
**Pull request by obra**
This is a bit cleaner than ./node_modules/bin

### CODE REVIEW

**Comment by RobMackie** [comment]
Jesse - I was really liking this. I ran it. A good bit of formatting on the Config page General tab has just disappeared. Any idea why. Wondering what using npx changed that caused that. The Foundation library, the treatment of css files? was it that a script is not moving files the same way they used to be moved? I'll try to find time to look into it, but not going to merge it until we know. Let me know you figure it out.

**Comment by obra** [comment]
One *possibility* is that the existing targets result in you running a local webpack rather than the one you've specified in the package.json 

I can demo this in another project:

```
# ➜  Chrysalis git:(system-info-to-main-proc) ✗
;webpack --version
5.73.0
# ➜  Chrysalis git:(system-info-to-main-proc) ✗
;npx webpack --version
4.46.0
```


Can you try for me, in a Fabmo-Engine checkout:

```
webpack --version
npx webpack --version
eslint --version
npx eslint --version
jest --version
npx jest --version
```

**Review by RobMackie — CHANGES_REQUESTED** [review]
There are side effects on page format (the config page tab for general settings) Worries me that it also changed other things. Can we figure it out and make sure it's just formating and maybe even fix it? or is it a move forward only change?

**Comment by obra** [comment]
> There are side effects on page format (the config page tab for general settings) Worries me that it also changed other things. Can we figure it out and make sure it's just formating and maybe even fix it? or is it a move forward only change?

This *should* have been a no-op in terms of functionality, but I think that it's exposed that certain tools have been run as "whatever the developer has installed system-wide locally" rather than the project-bundled versions.

**Comment by RobMackie** [comment]
2 anomalous things to report. Ran the same image this afternoon without an npm install and without an npm run dev.

The display was normal. Maybe I had some other problem or a problem with my browser. I'll try a fresh install/run and see what happens. 

Meanhwhile here is what I saw with versions. Figure it shows that we're running the versions from npm install. This is directly on the pi and from the root user so that it's the same as the install.

root@fabmo:/fabmo# webpack --version
bash: webpack: command not found
root@fabmo:/fabmo# eslint --version
bash: eslint: command not found
root@fabmo:/fabmo# jest --version
bash: jest: command not found
## so not coming from a global install.

root@fabmo:/fabmo# npx webpack --version
webpack: 5.44.0
webpack-cli: 4.9.2
webpack-dev-server 4.9.0
root@fabmo:/fabmo# npx eslint --version
v8.17.0
root@fabmo:/fabmo# npx jest --version
27.5.1

We have a lot of "^" in the the package.json. The versions above all fit when taking the "^" into account.  I'm curious - in your experience - is using "^" a best practice for a released product? or moving to specific verssions in the package.json.




> One _possibility_ is that the existing targets result in you running a local webpack rather than the one you've specified in the package.json
> 
> I can demo this in another project:
> 
> ```
> # ➜  Chrysalis git:(system-info-to-main-proc) ✗
> ;webpack --version
> 5.73.0
> # ➜  Chrysalis git:(system-info-to-main-proc) ✗
> ;npx webpack --version
> 4.46.0
> ```
> 
> Can you try for me, in a Fabmo-Engine checkout:
> 
> ```
> webpack --version
> npx webpack --version
> eslint --version
> npx eslint --version
> jest --version
> npx jest --version
> ```

**Comment by obra** [comment]
On Wed, Jun 8, 2022, at 11:11 AM, Rob Mackie wrote:
> 
> 
> 2 anomalous things to report. Ran the same image this afternoon without an npm install and without an npm run dev.
> 
> The display was normal. Maybe I had some other problem or a problem with my browser. I'll try a fresh install/run and see what happens.
> 
> Meanhwhile here is what I saw with versions. Figure it shows that we're running the versions from npm install. This is directly on the pi and from the root user so that it's the same as the install.
> 
> 
> 
> ***@***.***:/fabmo# webpack --version
> bash: webpack: command not found
> ***@***.***:/fabmo# eslint --version
> bash: eslint: command not found
> ***@***.***:/fabmo# jest --version
> bash: jest: command not found
> 
> 
> so not coming from a global install.
> 

Ok. You should reject this PR. I don't think my change caused the weirdness you're seeing, but I also don't believe npx is actually necessary here. I may follow up with an alternate PR to clean things up in a simpler way.

> We have a lot of "^" in the the package.json. The versions above all fit when taking the "^" into account. I'm curious - in your experience - is using "^" a best practice for a released product? or moving to specific verssions in the package.json.
> 

That's the normal way of things and what the package-lock.json is supposed to be for.  You *should* be committing package-lock.json to git.  https://nodejs.dev/learn/the-package-lock-json-file has some explanation of what that file does, but the short version is that it pins the exact releases that you're using.

If you don't commit package-lock.json to git (or have it in .gitignore like fabmo-engine does), npm will just pick the latest versions that match the package.json every time you do a clean checkout.

**Review by RobMackie — APPROVED** [review]
Looks good. i had a glitch of some kind that i cannot reproduce.

**Comment by RobMackie** [comment]
Oops I was busy testing things and didn't notice  your message. I think this change makes things better than they were. and it does appear to be a functional no-op. and we need to start using a lock file, so that comes next. If you have other ideas, we're open to them.

**Pull request merged**
